CREATE TABLE Articals (
	articalId int NOT NULL PRIMARY KEY,
	authorid int NOT NULL,
	seriesId int NOT NULL,
  sections varchar(255) NOT NULL,
  sectionLink varchar(255) NOT NULL,
  sectionType varchar(255) NOT NULL,
	articalTitle varchar(255) NOT NULL,
  articalSubTitle varchar(255) NOT NULL,
  publishedDate date NOT NULL,
  numberOfFavorites varchar(255),
  series boolean NOT NULL,
  seriesChapter INT NOT NULL,
  seriesType varchar(255) NOT NULL,
  useVideoInsteadOfImage boolean NOT NULL,
  coverImageOrVideo varchar(255) NOT NULL,
  artical text NOT NULL,
	FOREIGN KEY(authorid) REFERENCES Authors(authorid),
	FOREIGN KEY(seriesId) REFERENCES Series(seriesId)
);